### ISSUE TITLE
Resnet block is incorrectly implemented

### ISSUE THREAD

**Issue by nipunjindal** [gitlimlab/BicycleGAN-Tensorflow#2]
Hi,

The resnet block is incorrectly implemented the input is always 64 channel while the residual block channel size keeps changing.

If you are looking for pull requests, please let me know.

**Comment by youngwoon** [comment]
Thank you for the bug report.
I fixed it (https://github.com/gitlimlab/BicycleGAN-Tensorflow/commit/af75776f8ea7496672401c8e8c447420f79e9ce3).
